services:
  db:
    image: postgres:17
    container_name: phoenix_nest_postgres_container
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
